version: '3.8'

services:
  web-app:
    build:
      context: ./app1
      dockerfile: backend/Dockerfile
    image: secure-app1:latest
    container_name: my-secure-container
    init: true
    security_opt:
      - apparmor:unconfined
    expose:
      - "8001"
    environment:
      - DB_HOST=db
      - DB_NAME=secure_db
      - DB_USER=db_user
      - DB_PASSWORD=db_password
    networks:
      - lab-network
    depends_on:
      - db
    restart: always

  image-app:
    build:
      context: ./app2
      dockerfile: backend/Dockerfile
    image: secure-app2:latest
    container_name: image-app-container
    expose:
      - "8000"
    networks:
      - lab-network
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=secure_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lab-network
    restart: always

networks:
  lab-network:
    external: true

volumes:
  pgdata: