services:
  web-app:
    image: secure-app:latest
    container_name: my-secure-container
    init: true
    security_opt:
      - apparmor:unconfined
    build:
      context: ../app
      dockerfile: app1/backend/Dockerfile
    expose:
      - "8000"
    environment:
      - DB_HOST=db
      - DB_NAME=secure_db
      - DB_USER=db_user
      - DB_PASSWORD=db_password
    networks:
      - lab-network
    depends_on:
      - db
    restart: always

  image-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: image-app-container
    networks:
      - lab-network
    restart: always

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=secure_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lab-network
    restart: always

networks:
  lab-network:
    external: true

volumes:
  pgdata: