name: Deploy Application to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rebuild Docker Container
        run: |
          docker build -t secure-app:latest .
          docker stop my-secure-container || true
          docker rm my-secure-container || true
          docker run -d -p 8000:8000 --name my-secure-container secure-app:latest