name: Deploy Application to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: bandit SAST
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            ghcr.io/pycqa/bandit/bandit \
            -r /src/app -x /src/app/.venv -ll

      - name: Build Docker Image
        run: |
          docker build --no-cache -t secure-app:latest ./app

      - name: Scan Docker Image with Trivy
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.cache/trivy:/root/.cache/ \
            aquasec/trivy:0.49.1 \
            image --exit-code 1 --severity HIGH,CRITICAL secure-app:latest
          
      - name: Rebuild and Run Infrastructure via Docker Compose
        run: |
            cd ${{ github.workspace }}/infra/mail
            docker compose down --remove-orphans
            docker compose up -d --build
            sleep 
            docker exec mailserver setup email add user1@localdomain "password123" || true
            docker compose ps